default_language_version:
  python: python3.10
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0  # Use the ref you want to point at
      hooks:
      -   id: trailing-whitespace
      -   id: check-yaml
  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.15.0
      hooks:
      -   id: pyupgrade
  -   repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
      -   id: black
  -   repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
      -   id: isort
          name: isort (python)
  -   repo: https://github.com/jorisroovers/gitlint
      rev: v0.19.1
      hooks:
      -   id: gitlint